# ─────────────────────────────────────────────
# APPLICATION
# ─────────────────────────────────────────────
spring.application.name=account-service
server.port=8081

# ─────────────────────────────────────────────
# DATABASE — PostgreSQL
# ─────────────────────────────────────────────
# jdbc:postgresql://<host>:<port>/<database-name>
spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ─────────────────────────────────────────────
# JPA / HIBERNATE
# ─────────────────────────────────────────────
# update = Hibernate updates the schema automatically (DEV ONLY)
# validate = only validates, never changes schema (use in production)
# none = do nothing (production with Flyway/Liquibase managing schema)
spring.jpa.hibernate.ddl-auto=update

# Show the SQL Hibernate generates (useful for learning, disable in prod)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Tells Hibernate we are using PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
